#ifndef AI_H
#define AI_H

enum T_AI_TASK_FORCE_CMD {
    T_AI_TASK_FORCE_CMD_UNKNOWN_0,
    T_AI_TASK_FORCE_CMD_UNKNOWN_1,
    T_AI_TASK_FORCE_CMD_UNKNOWN_2,
    T_AI_TASK_FORCE_CMD_UNKNOWN_3,
    T_AI_TASK_FORCE_CMD_UNKNOWN_4,
};

enum T_AI_TASK_FORCE_STATUS {
    TASK_FORCE_STATUS_NONE = 0,
    TASK_FORCE_STATUS_UNKNOWN_1,
    TASK_FORCE_STATUS_UNKNOWN_2,
    TASK_FORCE_STATUS_UNKNOWN_3,
    TASK_FORCE_STATUS_UNKNOWN_4,
    TASK_FORCE_STATUS_UNKNOWN_5,
    TASK_FORCE_STATUS_UNKNOWN_6,
    TASK_FORCE_STATUS_UNKNOWN_7,
    TASK_FORCE_STATUS_UNKNOWN_8,
    TASK_FORCE_STATUS_UNKNOWN_9,
    TASK_FORCE_STATUS_UNKNOWN_10,
};

enum T_AI_TASK_FORCE_TYPE {
    TASK_FORCE_TYPE_NONE = 0,
    TASK_FORCE_TYPE_RESERVOIR,
    TASK_FORCE_TYPE_UNKNOWN_2,
    TASK_FORCE_TYPE_UNKNOWN_3,
    TASK_FORCE_TYPE_UNKNOWN_4,
    AI_TASK_FORCE_TYPE_PRIESTS        = 8,
    AI_TASK_FORCE_TYPE_DARK_GARDENERS = 11,
    AI_TASK_FORCE_TYPE_SHAMANS        = 12,
    AI_TASK_FORCE_TYPE_MANAKOPTERS    = 13
};

enum T_AI_WARRIOR_TYPE {
    AI_WARRIOR_TYPE_NONE           = 0,
    AI_WARRIOR_TYPE_SWORDMAN       = 2,
    AI_WARRIOR_TYPE_BOWMAN         = 3,
    AI_WARRIOR_TYPE_FIGHTER_UNIQUE = 4,
    AI_WARRIOR_TYPE_SQUAD_LEADER   = 5,
    AI_WARRIOR_TYPE_PRIEST         = 6,
    AI_WARRIOR_TYPE_MISC_UNIT      = 7,
    AI_WARRIOR_TYPE_VEHICLE_MISC   = 9,
    AI_WARRIOR_TYPE_TOWER_BUILDING = 12,
    AI_WARRIOR_TYPE_LAST           = 13,
};

#define AI_WARRIOR_TYPE_SOLDIER_MASK (1 << AI_WARRIOR_TYPE_SWORDMAN | 1 << AI_WARRIOR_TYPE_BOWMAN | 1 << AI_WARRIOR_TYPE_FIGHTER_UNIQUE | 1 << AI_WARRIOR_TYPE_SQUAD_LEADER)
static_assert(AI_WARRIOR_TYPE_SOLDIER_MASK == 60); // See e.g. in 0x15df900, where we select all

enum T_AI_TASK_FORCE_CLASS {
    AI_TASK_FORCE_CLASS_NONE      = 0,
    AI_TASK_FORCE_CLASS_RESERVOIR = 1,
    AI_TASK_FORCE_CLASS_SQUAD     = 2,
    AI_TASK_FORCE_CLASS_PRIESTS   = 3,

    AI_TASK_FORCE_CLASS_GROUP       = 6, // just a guess, but CTaskForceEx checks this in a Group call
    AI_TASK_FORCE_CLASS_SHAMANS     = 7,
    AI_TASK_FORCE_CLASS_MANAKOPTERS = 8,
    AI_TASK_FORCE_CLASS_MAX         = 9,
};

enum T_RESULT {
    RESULT_INVALID   = 0,
    RESULT_FAILED    = 1,
    RESULT_UNKNOWN_2 = 2, //As in, I dont know what the name is
    RESULT_ADDED     = 3,
    RESULT_REMOVED   = 4, //Just a guess to be added and removed - seems to be used in CAITaskForceSquard mostly in regards to that semantic
};

enum T_AI_ENTITY_INFO_EX_CLASS {
    AI_ENTITY_INFO_EX_CLASS_TOWER = 0,
    AI_ENTITY_INFO_EX_CLASS_MAX,
};

#endif //AI_H
