#ifndef ANIMALS_H
#define ANIMALS_H

#include "DefineTransformers.h"

#define ANIMALS \
    X(0, ANIMAL_NO_ANIMAL) \
    X(1, ANIMAL_BOAR) \
    X(2, ANIMAL_DARKBUG) \
    X(3, ANIMAL_DARKBUGBIG) \
    X(4, ANIMAL_DEERFE) \
    X(5, ANIMAL_DEERMA) \
    X(6, ANIMAL_FOX) \
    X(7, ANIMAL_CHICKEN) \
    X(8, ANIMAL_JAGUAR) \
    X(9, ANIMAL_RABBIT) \
    X(10, ANIMAL_DOLPHIN) \
    X(11, ANIMAL_NESSY) \
    X(12, ANIMAL_SHARK) \
    X(13, ANIMAL_WILDBEAR) \
    X(14, ANIMAL_WOLF) \
    X(15, ANIMAL_FISH) \
    X(16, ANIMAL_RABBIT2) \
    X(17, ANIMAL_BULL)

#define ANIMAL_EFFECTS \
    X(0, ANIMAL_NO_ANIMAL_WALK) \
    X(1, ANIMAL_BOAR_SMELL) \
    X(2, ANIMAL_BOAR_WALK) \
    X(3, ANIMAL_BOAR_DIE) \
    X(4, ANIMAL_DARKBUG_IDLE) \
    X(5, ANIMAL_DARKBUG_WALK) \
    X(6, ANIMAL_DARKBUGBIG_IDLE) \
    X(7, ANIMAL_DARKBUGBIG_WALK) \
    X(8, ANIMAL_DEERFE_SMELL) \
    X(9, ANIMAL_DEERFE_WALK) \
    X(10, ANIMAL_DEERFE_JUMP) \
    X(11, ANIMAL_DEERFE_DIE) \
    X(12, ANIMAL_DEERMA_SMELL) \
    X(13, ANIMAL_DEERMA_WALK) \
    X(14, ANIMAL_DEERMA_JUMP) \
    X(15, ANIMAL_DEERMA_DIE) \
    X(16, ANIMAL_FOX_SMELL) \
    X(17, ANIMAL_FOX_WALK) \
    X(18, ANIMAL_CHICKEN_PICK) \
    X(19, ANIMAL_CHICKEN_WALK) \
    X(20, ANIMAL_JAGUAR_SMELL) \
    X(21, ANIMAL_JAGUAR_WALK) \
    X(22, ANIMAL_RABBIT_SMELL) \
    X(23, ANIMAL_RABBIT_WALK) \
    X(24, ANIMAL_RABBIT_DIE) \
    X(25, ANIMAL_DOLPHIN_SWIM) \
    X(26, ANIMAL_NESSY_VIEW_LEFT) \
    X(27, ANIMAL_NESSY_VIEW_RIGHT) \
    X(28, ANIMAL_SHARK_SWIM) \
    X(29, ANIMAL_WILDBEAR_WALK) \
    X(30, ANIMAL_WILDBEAR_SMELL) \
    X(31, ANIMAL_WILDBEAR_STANDUP) \
    X(32, ANIMAL_WILDBEAR_FIGHT) \
    X(33, ANIMAL_WILDBEAR_DIE) \
    X(34, ANIMAL_WOLF_WALK) \
    X(35, ANIMAL_WOLF_HOWL) \
    X(36, ANIMAL_FISH_SWIM) \
    X(37, ANIMAL_RABBIT2_SMELL) \
    X(38, ANIMAL_RABBIT2_WALK) \
    X(39, ANIMAL_RABBIT2_DIE) \
    X(40, ANIMAL_BULL_WALK)

#define X TO_ENUM

enum SIV_ANIMALS {
    ANIMALS

    ANIMAL_EFFECTS
    SIV_ANIMAL_MAX
};
#undef X

#define X TO_PAIR
SConfigTypeString s_sAnimalDefines[] = {
    ANIMALS
};
#undef X


#endif //ANIMALS_H
