#ifndef S4_MAIN_BUILDINGS_H
#define S4_MAIN_BUILDINGS_H

#include "DefineTransformers.h"

// address=[0x377C0D0]
#define BUILDINGS \
    X(0,BUILDING_NO_BUILDING) \
    X(1,BUILDING_WOODCUTTERHUT) \
    X(2,BUILDING_FORESTERHUT) \
    X(3,BUILDING_SAWMILL) \
    X(4,BUILDING_STONECUTTERHUT) \
    X(5,BUILDING_WATERWORKHUT) \
    X(6,BUILDING_FISHERHUT) \
    X(7,BUILDING_HUNTERHUT) \
    X(8,BUILDING_SLAUGHTERHOUSE) \
    X(9,BUILDING_MILL) \
    X(10,BUILDING_BAKERY) \
    X(11,BUILDING_GRAINFARM) \
    X(12,BUILDING_ANIMALRANCH) \
    X(13,BUILDING_DONKEYRANCH) \
    X(14,BUILDING_STONEMINE) \
    X(15,BUILDING_IRONMINE) \
    X(16,BUILDING_GOLDMINE) \
    X(17,BUILDING_COALMINE) \
    X(18,BUILDING_SULFURMINE) \
    X(19,BUILDING_SMELTGOLD) \
    X(20,BUILDING_SMELTIRON) \
    X(21,BUILDING_TOOLSMITH) \
    X(22,BUILDING_WEAPONSMITH) \
    X(23,BUILDING_VEHICLEHALL) \
    X(24,BUILDING_BARRACKS) \
    X(25,BUILDING_CHARCOALMAKER) \
    X(26,BUILDING_TRAININGCENTER) \
    X(27,BUILDING_HEALERHUT) \
    X(28,BUILDING_AMMOMAKERHUT) \
    X(29,BUILDING_GUNPOWDERMAKERHUT) \
    X(30,BUILDING_LANDSCAPEMAKERHUT) \
    X(31,BUILDING_SHIPYARD) \
    X(32,BUILDING_PORT) \
    X(33,BUILDING_MARKETPLACE) \
    X(34,BUILDING_STORAGEAREA) \
    X(35,BUILDING_VINYARD) \
    X(36,BUILDING_AGAVEFARMERHUT) \
    X(37,BUILDING_TEQUILAMAKERHUT) \
    X(38,BUILDING_BEEKEEPERHUT) \
    X(39,BUILDING_MEADMAKERHUT) \
    X(40,BUILDING_RESIDENCESMALL) \
    X(41,BUILDING_RESIDENCEMEDIUM) \
    X(42,BUILDING_RESIDENCEBIG) \
    X(43,BUILDING_SMALLTEMPLE) \
    X(44,BUILDING_BIGTEMPLE) \
    X(45,BUILDING_LOOKOUTTOWER) \
    X(46,BUILDING_GUARDTOWERSMALL) \
    X(47,BUILDING_GUARDTOWERBIG) \
    X(48,BUILDING_CASTLE) \
    X(49,BUILDING_MUSHROOMFARM) \
    X(50,BUILDING_DARKTEMPLE) \
    X(51,BUILDING_FORTRESS) \
    X(52,BUILDING_PORTA) \
    X(53,BUILDING_PORTB) \
    X(54,BUILDING_PORTC) \
    X(55,BUILDING_PORTD) \
    X(56,BUILDING_PORTE) \
    X(57,BUILDING_PORTF) \
    X(58,BUILDING_SHIPYARDA) \
    X(59,BUILDING_SHIPYARDB) \
    X(60,BUILDING_SHIPYARDC) \
    X(61,BUILDING_SHIPYARDD) \
    X(62,BUILDING_SHIPYARDE) \
    X(63,BUILDING_SHIPYARDF) \
    X(64,BUILDING_EYECATCHER01) \
    X(65,BUILDING_EYECATCHER02) \
    X(66,BUILDING_EYECATCHER03) \
    X(67,BUILDING_EYECATCHER04) \
    X(68,BUILDING_EYECATCHER05) \
    X(69,BUILDING_EYECATCHER06) \
    X(70,BUILDING_EYECATCHER07) \
    X(71,BUILDING_EYECATCHER08) \
    X(72,BUILDING_EYECATCHER09) \
    X(73,BUILDING_EYECATCHER10) \
    X(74,BUILDING_EYECATCHER11) \
    X(75,BUILDING_EYECATCHER12) \
    X(76,BUILDING_SHIPYARDG) \
    X(77,BUILDING_SHIPYARDH) \
    X(78,BUILDING_PORTG) \
    X(79,BUILDING_PORTH) \
    X(80,BUILDING_MANACOPTERHALL) \
    X(81,BUILDING_SUNFLOWEROILMAKERHUT) \
    X(82,BUILDING_SUNFLOWERFARMERHUT)

#define X(id, name) TO_ENUM(id,name)

enum S4_BUILDING_ENUM {
    BUILDINGS
    BUILDING_MAX
};
#undef X

#endif //S4_MAIN_BUILDINGS_H
