#ifndef EFFECTS_H
#define EFFECTS_H

#include "DefineTransformers.h"


constexpr int EFFECTS_MAX = 0x1000;
constexpr int MAX_EFFECT_COUNT = 4095;

constexpr int EFFECT_ANGEL_LAST = 2;
constexpr int EFFECT_MISSILE_LAST = 9;

constexpr int FIRST_REAL_EFFECT = 2;
constexpr int FREE_EFFECTS_LIST_HEAD = 1;

#define EFFECTS \
    X(0, EFFECT_NO_EFFECT) \
    X(1, EFFECT_FLYINGARROWS) \
    X(2, EFFECT_IMPACT_GROUND) \
    X(3, EFFECT_IMPACT_WATER) \
    X(4, EFFECT_IMPACT_HOUSE) \
    X(5, EFFECT_FLYINGSTONE3) \
    X(6, EFFECT_SWAMPBUBBLE) \
    X(7, EFFECT_FLAGMINI) \
    X(8, EFFECT_STANDARTE) \
    X(9, EFFECT_FLYINGSTONE1) \
    X(10, EFFECT_FLYINGSTONE2) \
    X(11, EFFECT_BUTTERFLY1) \
    X(12, EFFECT_BUTTERFLY2) \
    X(13, EFFECT_BUTTERFLY3) \
    X(14, EFFECT_BIRD) \
    X(15, EFFECT_SEAGULL1) \
    X(16, EFFECT_SEAGULL2) \
    X(17, EFFECT_DUCKMA) \
    X(18, EFFECT_DUCKFE) \
    X(19, EFFECT_BOWMAN_STONE) \
    X(20, EFFECT_SPORECLOUD_GROW) \
    X(21, EFFECT_SPORECLOUD_GROWNUP) \
    X(22, EFFECT_FIREBALLS) \
    X(23, EFFECT_VMAGIC_THORSHAMMER) \
    X(24, EFFECT_RMAGIC_GIFTOFGOD) \
    X(25, EFFECT_MMAGIC_GIFTOFGOD) \
    X(26, EFFECT_VMAGIC_GIFTOFGOD) \
    X(27, EFFECT_RMAGIC_CHANGEGOOD) \
    X(28, EFFECT_MMAGIC_CHANGEGOOD) \
    X(29, EFFECT_VMAGIC_CHANGEGOOD) \
    X(30, EFFECT_RMAGIC_SMELTSNOW) \
    X(31, EFFECT_MMAGIC_SMELTSNOW) \
    X(32, EFFECT_VMAGIC_SMELTSNOW) \
    X(33, EFFECT_VMAGIC_BLOODRUSH) \
    X(34, EFFECT_VMAGIC_BLOODRUSH_SMALL) \
    X(35, EFFECT_RMAGIC_BARBARIAN) \
    X(36, EFFECT_RMAGIC_REFRESHRESOURCES) \
    X(37, EFFECT_MMAGIC_FERTILITY) \
    X(38, EFFECT_MMAGIC_TELEPORT) \
    X(39, EFFECT_RMAGIC_DEFENSESHIELD) \
    X(40, EFFECT_MMAGIC_PUNISHSOLDIERS) \
    X(41, EFFECT_MMAGIC_RAISERANK) \
    X(42, EFFECT_VMAGIC_INCREASEANIMALS) \
    X(43, EFFECT_VMAGIC_INCREASEANIMALS_SMALL) \
    X(44, EFFECT_VMAGIC_FREEZESOLDIERS) \
    X(45, EFFECT_VMAGIC_FREEZESOLDIERS_SMALL) \
    X(46, EFFECT_VMAGIC_FRIGHTENSOLDIERS) \
    X(47, EFFECT_MMAGIC_STONECURSE) \
    X(48, EFFECT_RMAGIC_FOODFISH) \
    X(49, EFFECT_RMAGIC_JUPITERSLIGHTNING) \
    X(50, EFFECT_RMAGIC_JUPITERSLIGHTNING_SMALL) \
    X(51, EFFECT_MAGIC_PILE01) \
    X(52, EFFECT_MAGIC_PILE02) \
    X(53, EFFECT_MAGIC_PILE03) \
    X(54, EFFECT_MAGIC_SETTLER01) \
    X(55, EFFECT_MAGIC_SETTLER02) \
    X(56, EFFECT_MAGIC_SETTLER03) \
    X(57, EFFECT_TUTORIAL_ARROW) \
    X(58, EFFECT_MUSHROOMFARM_BUILD) \
    X(59, EFFECT_BREADSMOKE) \
    X(60, EFFECT_CRUSHBIG) \
    X(61, EFFECT_DESTROYBIG) \
    X(62, EFFECT_CRUSHSMALL) \
    X(63, EFFECT_DESTROYSMALL) \
    X(64, EFFECT_ANIM_SMOKE) \
    X(65, EFFECT_SLIMEBALL) \
    X(66, EFFECT_CRASH) \
    X(67, EFFECT_DARKSMOKE01) \
    X(68, EFFECT_DARKSMOKE02) \
    X(69, EFFECT_DARKSMOKE03) \
    X(70, EFFECT_GRAYSMOKE01) \
    X(71, EFFECT_GRAYSMOKE02) \
    X(72, EFFECT_GRAYSMOKE03) \
    X(73, EFFECT_SMOKE01) \
    X(74, EFFECT_SMOKE02) \
    X(75, EFFECT_SMOKE03) \
    X(76, EFFECT_SLAVEFX) \
    X(77, EFFECT_MUSHROOMFARM_CRASH) \
    X(78, EFFECT_DARKFLAME) \
    X(79, EFFECT_SMALLSMOKE01) \
    X(80, EFFECT_SMALLSMOKE02) \
    X(81, EFFECT_SMALLSMOKE03) \
    X(82, EFFECT_SMALLSMOKE04) \
    X(83, EFFECT_SMALLSMOKE05) \
    X(84, EFFECT_FLYINGARROWS2) \
    X(85, EFFECT_IMPACT_SHIP)

#define EFFECTS_2 \
    X(100,EFFECT_2_NO_EFFECT) \
    X(101,EFFECT_2_DMAGIC_DARKDRY) \
    X(102,EFFECT_2_DMAGIC_TELEPORT) \
    X(103,EFFECT_2_TMAGIC_DELPHIORACLE) \
    X(104,EFFECT_2_TMAGIC_MAGICDOOR) \
    X(105,EFFECT_2_TMAGIC_MAKEPEACE) \
    X(106,EFFECT_2_TMAGIC_MINERFOOD) \
    X(107,EFFECT_2_TFLYINGBULLET) \
    X(108,EFFECT_2_TMAGIC_INVISIBLE) \
    X(109,EFFECT_2_DMANAKOPTER_TURN) \
    X(110,EFFECT_2_DMANAKOPTERSHADOW) \
    X(111,EFFECT_2_DMANAKOPTER_ROTOR) \
    X(112,EFFECT_2_TFLYINGBIGSTONE) \
    X(113,EFFECT_2_TFLYINGSMALLSTONE) \
    X(114,EFFECT_2_DMANAKOPTER_EXPLODE) \
    X(115,EFFECT_2_TIMPACT_EXPLOSIVEARROW)

enum T_VISUALIZE_FUNC : BYTE {
    VISUALIZE_FUNC_NOP_1           = 0,
    VISUALIZE_FUNC_NOP_2           = 1,
    VISUALIZE_FUNC_EFFECT          = 2,
    VISUALIZE_FUNC_ANGEL           = 3,
    VISUALIZE_FUNC_ARROW           = 4,
    VISUALIZE_FUNC_CANNONBALL      = 5,
    VISUALIZE_FUNC_SPORE_CLOUD     = 6,
    VISUALIZE_FUNC_STAGNANT_ANIMAL = 7,
    VISUALIZE_FUNC_MOVING_EFFECT   = 8,
    VISUALIZE_FUNC_TOP_EFFECT      = 9,
    VISUALIZE_FUNC_TOP_FIREBALL    = 10,
    VISUALIZE_FUNC_ATTACHED_EFFECT = 11,
    VISUALIZE_FUNC_MAX
};

enum T_EFFECT_ANGEL {
    EFFECT_ANGEL_NONE = 0,
};

#define X TO_ENUM

enum T_S4_EFFECTS {
    EFFECTS
    EFFECT_MAX
};

enum T_S4_EFFECTS_2 {
    EFFECTS_2
    EFFECT_2_MAX
};

#undef X

#endif //EFFECTS_H
