#ifndef EVENTS_H
#define EVENTS_H

#include "DefineTransformers.h"

#define GENERIC_EVENTS \
X(0x0, GENERIC_EVENT_LOAD_CONFIG) \
X(0x2, GENERIC_EVENT_UPDATE_WINDOW_POS) \
X(0x3, GENERIC_EVENT_REBUILD_GFX) \
X(0x11, GENERIC_EVENT_REBUILD_GFX_2) \
X(0x4, GENERIC_EVENT_QUIT_1) \
X(0x76, GENERIC_EVENT_QUIT_2) \
X(0x6C, GENERIC_EVENT_REQUEST_QUIT) \
X(0xB, GENERIC_EVENT_KEY_PRESS) \
X(0x14, GENERIC_EVENT_KEY_UP) \
X(0xD, GENERIC_EVENT_SHOW_MANUAL) \
X(0xC, GENERIC_EVENT_TOGGLE_FULLSCREEN) \
X(0x15, GENERIC_EVENT_MOUSE_POS) \
X(0x16, GENERIC_EVENT_FOCUS) \
X(0x19, GENERIC_EVENT_START_TICK)


#define X TO_ENUM

enum T_S4_GENERIC_EVENT {
    GENERIC_EVENTS
};

#undef X

#endif //EVENTS_H
