#ifndef INPUT_H
#define INPUT_H

#include "DefineTransformers.h"

constexpr int MAX_SELECTED_ENTITIES = 100;

#define INPUT_STATES \
X(0, WAIT_STATE) \
X(1, SELECT_STATE) \
X(2, BUILDING_SELECT_STATE) \
X(3, SET_WORKINGAREA_STATE) \
X(4, TRY_BUILD_STATE) \
X(5, TRY_BUILD_STATE_EX) \
X(6, TRY_BUILD_STATE_SEARCH) \
X(7, CHOOSE_TRADE_DEST_STATE) \
X(8, CHOOSE_SPELL_DEST_STATE) \
X(9, SET_SECOND_PATROL_POS_STATE) \
X(10, ZOOM_AREA_STATE)

#define X TO_ENUM

enum T_INPUT_STATE {
    INPUT_STATES
    STATE_MAX
};

#undef X

#endif //INPUT_H
