#ifndef LOGIC_H
#define LOGIC_H

#include "DefineTransformers.h"

#define LOGIC_MSGS \
    X(0, LOGIC_MSG_BEGIN) \
X(1, LOGIC_MSG_DEFAULT) \
X(2, LOGIC_MSG_NEW_DIALOG) \
X(3, LOGIC_MSG_SHOWWORKINGAREA) \
X(4, LOGIC_MSG_TRYCRUSH_BUILDING) \
X(5, LOGIC_MSG_CRUSH_BUILDING) \
X(6, LOGIC_MSG_SWITCH_BUILDING) \
X(7, LOGIC_MSG_PRIO_BUILDING_SITE) \
X(8, LOGIC_MSG_NEXT_BUILDING) \
X(9, LOGIC_MSG_CHOOSE_TRADE_DEST) \
X(10, LOGIC_MSG_GOTO_POS) \
X(11, LOGIC_MSG_FORCE_GOTO) \
X(12, LOGIC_MSG_STAND_GROUND) \
X(13, LOGIC_MSG_WAYPOINT) \
X(14, LOGIC_MSG_PATROL ) \
X(15, LOGIC_MSG_INJURED_OUT) \
X(16, LOGIC_MSG_ESCORT) \
X(17, LOGIC_MSG_EMPTY) \
X(18, LOGIC_MSG_LOAD) \
X(19, LOGIC_MSG_MORPH2FOUNDATIONCART) \
X(20, LOGIC_MSG_MORPH2CART) \
X(21, LOGIC_MSG_FOUNDATION) \
X(22, LOCIC_MSG_GOTO_VEHICLE_GROUP_MENU) \
X(23, LOGIC_MSG_MORPH_2_CARRIER) \
X(24, LOGIC_MSG_ENTITY_TO_SELECTION) \
X(25, LOGIC_MSG_SELECT_KIND) \
X(26, LOGIC_MSG_SELECT_TYPE) \
X(27, LOGIC_MSG_NEXT_VEHICLE) \
X(28, LOGIC_MSG_INIT_BUILD_MENU) \
X(29, LOGIC_MSG_INIT_SETTLERSTATISTIC_MENU) \
X(30, LOGIC_MSG_INIT_FREECARRIER_MENU) \
X(31, LOGIC_MSG_INIT_SETTLERPRODUCTION_MENU) \
X(32, LOGIC_MSG_INIT_AVAILABLE_GOODS_MENU) \
X(33, LOGIC_MSG_INIT_TRANSPORTPRIORITY_MENU) \
X(34, LOGIC_MSG_INIT_GOODDISTRIBUTION_MENU) \
X(35, LOGIC_MSG_INIT_STATISTIC) \
X(36, LOGIC_MSG_INIT_ECONOMYGAME_MENU) \
X(37, LOGIC_MSG_TRYBUILD) \
X(38, LOGIC_MSG_MARK_NEXT_BUILDING) \
X(39, LOGIC_MSG_BUILDING_MATERIAL) \
X(40, LOGIC_MSG_SWITCH_LOCAL) \
X(41, LOGIC_MSG_SEARCH_UNIT) \
X(42, LOGIC_MSG_UNIT_RESERVATION) \
X(43, LOGIC_MSG_GET_TOWER_WARRIOR) \
X(44, LOGIC_MSG_THROW_OUT_TOWER_WARRIOR) \
X(45, LOGIC_MSG_GOOD_DELIVERING_CHANGED) \
X(46, LOGIC_MSG_TRANSPORT_PRIO) \
X(47, LOGIC_MSG_DESTROY_VEHICLE) \
X(48, LOGIC_MSG_DESTROY_CART_WARMACHINE) \
X(49, LOGIC_MSG_INIT_MAGIC_SIDEBAR) \
X(50, LOGIC_MSG_INIT_GROUP_SIDEBAR) \
X(51, LOGIC_MSG_INIT_ADDSOLDIER_SIDEBAR) \
X(52, LOGIC_MSG_INIT_TOOL_SIDEBAR) \
X(53, LOGIC_MSG_INIT_WEAPON_SIDEBAR) \
X(54, LOGIC_MSG_INIT_SPECIALIST_SIDEBAR) \
X(55, LOGIC_MSG_INIT_GOODSOUT_SIDEBAR) \
X(56, LOGIC_MSG_INIT_TRADE_SIDEBAR) \
X(57, LOGIC_MSG_INIT_STORAGE_SIDBAR) \
X(58, LOGIC_MSG_INIT_EYECATCHER_SIDBAR) \
X(59, LOGIC_MSG_INIT_ADDVEHICLE_SIDBAR) \
X(60, LOGIC_MSG_CLOSED_SIDEBAR) \
X(61, LOGIC_MSG_UNIT_PRODUCTION) \
X(62, LOGIC_MSG_URGENT_PRODUCTION) \
X(63, LOGIC_MSG_WEAPON_PERCENT_CHANGED) \
X(64, LOGIC_MSG_WEAPONAUTOPRODUCTION) \
X(65, LOGIC_MSG_TRANSPORT_GOOD) \
X(66, LOGIC_MSG_TRADE_WITH) \
X(67, LOGIC_MSG_TRADE_GOOD) \
X(68, LOGIC_MSG_STORAGE_GOOD_SWITCH) \
X(69, LOGIC_MSG_VEHICLE_PRODUCTION) \
X(70, LOGIC_MSG_DEFINE_GROUP) \
X(71, LOGIC_MSG_GROUP_TO_SELECTION) \
X(72, LOGIC_MSG_SELECT_GROUP) \
X(73, LOGIC_MSG_FOCUS_GROUP) \
X(74, LOGIC_MSG_TRY_CAST_SPELL) \
X(75, LOGIC_MSG_MINIMAP) \
X(76, LOGIC_MSG_CHOOSE_OBSERVE_TARGET) \
X(77, LOGIC_MSG_LMB) \
X(78, LOGIC_MSG_BOX_SELECTION) \
X(79, LOGIC_MSG_BOX_SELECTION_VIRTUAL) \
X(80, LOGIC_MSG_RMB) \
X(81, LOGIC_MSG_SPECIALIST_PRODUCTION) \
X(82, LOGIC_MSG_INIT_EXTRA_MENU) \
X(83, LOGIC_MSG_ZOOM_AREA) \
X(84, LOGIC_MSG_END)

#define NET_LOGIC_MSGS \
    X(5000, NET_LOGIC_MSG_BEGIN) \
    X(5001, NET_LOGIC_MSG_SET_WORKINGAREA) \
    X(5002, NET_LOGIC_MSG_CRUSH_BUILDING) \
    X(5003, NET_LOGIC_MSG_SWITCH_BUILDING) \
    X(5004, NET_LOGIC_MSG_PRIO_BUILDING_SITE) \
    X(5005, NET_LOGIC_MSG_TRADE_TARGET) \
    X(5006, NET_LOGIC_MSG_TRANSPORT_GOOD) \
    X(5007, NET_LOGIC_MSG_TRADE_WITH) \
    X(5008, NET_LOGIC_MSG_TRADE_GOOD) \
    X(5009, NET_LOGIC_MSG_UNLOAD) \
    X(5010, NET_LOGIC_MSG_LOAD_AMMO) \
    X(5011, NET_LOGIC_MSG_CREATE_SETTLEMENT) \
    X(5012, NET_LOGIC_MSG_MORPH2_FOUNDATIONCART) \
    X(5013, NET_LOGIC_MSG_MORPH2_CART) \
    X(5014, NET_LOGIC_MSG_GOTO_POS) \
    X(5015, NET_LOGIC_MSG_FORCE_GOTO) \
    X(5016, NET_LOGIC_MSG_STAND_GROUND) \
    X(5017, NET_LOGIC_MSG_SET_WAYPOINT) \
    X(5018, NET_LOGIC_MSG_PATROL) \
    X(5019, NET_LOGIC_MSG_INJURED_OUT) \
    X(5020, NET_LOGIC_MSG_ESCORT) \
    X(5021, NET_LOGIC_MSG_MORPH_2_CARRIER) \
    X(5022, NET_LOGIC_MSG_ENTITY_TO_SELECTION) \
    X(5023, NET_LOGIC_MSG_SELECT_KIND) \
    X(5024, NET_LOGIC_MSG_SELECT_TYPE) \
    X(5025, NET_LOGIC_MSG_BUILD_BUILDING) \
    X(5026, NET_LOGIC_MSG_SEARCH_UNIT) \
    X(5027, NET_LOGIC_MSG_UNIT_RESERVATION) \
    X(5028, NET_LOGIC_MSG_CHANGE_GOOD_DISTRIBUTION) \
    X(5029, NET_LOGIC_MSG_CHANGE_TRANSPORT_PRIORITY) \
    X(5030, NET_LOGIC_MSG_DESTROY_VEHICLE) \
    X(5031, NET_LOGIC_MSG_SET_TOWER_WARRIOR) \
    X(5032, NET_LOGIC_MSG_THROW_OUT_TOWER_WARRIOR) \
    X(5033, NET_LOGIC_MSG_URGENT_PRODUCTION) \
    X(5034, NET_LOGIC_MSG_WEAPON_PERCENT) \
    X(5035, NET_LOGIC_MSG_WEAPON_AUTO) \
    X(5036, NET_LOGIC_MSG_STANDARD_PRODUCTION) \
    X(5037, NET_LOGIC_MSG_SET_GOOD_SWITCH) \
    X(5038, NET_LOGIC_MSG_SET_JOB_PERCENT) \
    X(5039, NET_LOGIC_MSG_RECRUITE_SPECIALIST) \
    X(5040, NET_LOGIC_MSG_VEHICLE_PRODUCTION) \
    X(5041, NET_LOGIC_MSG_DEFINE_GROUP) \
    X(5042, NET_LOGIC_MSG_GROUP_TO_SELECTION) \
    X(5043, NET_LOGIC_MSG_SELECT_GROUP) \
    X(5044, NET_LOGIC_MSG_STORE_GOOD) \
    X(5045, NET_LOGIC_MSG_SET_GOOD_PRIORITY) \
    X(5046, NET_LOGIC_MSG_SET_TRADE) \
    X(5047, NET_LOGIC_MSG_SET_UNIT_PRODUCTION) \
    X(5048, NET_LOGIC_MSG_CAST_SPELL) \
    X(5049, NET_LOGIC_MSG_DESTROY_CART_WARMACHINE) \
    X(5050, NET_LOGIC_MSG_SET_TRADE_PLAYER_STATUS) \
    X(5053, NET_LOGIC_MSG_END)

#define X TO_ENUM

enum T_LOGIC_MSG {
    LOGIC_MSGS
};

#undef X

enum T_LOGIC_HANDLERS {
    HandleInternalError     = 0,
    Default                 = 1,
    NewDialogClear          = 17,
    EmptyFunct              = 3,
    TryBuild                = 4,
    Build                   = 5,
    ShowWorkingArea         = 6,
    SetWorkingArea          = 7,
    TryCrushBuilding        = 8,
    CrushBuilding           = 9,
    SwitchBuilding          = 10,
    PrioBuildingSite        = 11,
    SelectNextBuilding      = 12,
    SelectBuilding          = 13,
    MarkNextBuilding        = 15,
    SelectNextVehicle       = 14,
    BuildingAmount          = 16,
    FillTower               = 18,
    EmptyTower              = 19,
    ChooseTradeDest         = 21,
    SelectTradeDest         = 22,
    TransportGoods          = 23,
    TradeWith               = 24,
    TradeGoods              = 25,
    SetTradePlayerStatus    = 26,
    PrepareBoxSelection     = 27,
    DotSelection            = 28,
    SelectTypeInSurrounding = 29,
    SelectGroup             = 30,
    GroupToSelection        = 31,
    DefineGroup             = 32,
    FocusGroup              = 33,
    SendTo                  = 34,
    ForceGoto               = 35,
    StandGround             = 36,
    ChooseSecondPatrolPos   = 37,
    SelectSecondPatrolPos   = 38,
    InjuredOut              = 40,
    MorphToCarrier          = 41,
    InitExtraMenu           = 20,
    InitEconomyGameMenu     = 56,
    GotoVehicleGroupMenu    = 39,
    SearchUnit              = 48,
    UnitReservation         = 49,
    ChooseSpellDest         = 42,
    SelectSpellDest         = 43,
    SwitchLocalGlobal       = 74,
    InitSettlerAmount       = 44,
    InitFreeCarrier         = 45,
    InitSettlerProduction   = 46,
    InitSettlerSearch       = 47,
    InitGoodAmount          = 50,
    InitTransportPrio       = 51,
    InitGoodDistribution    = 52,
    GoodDeliveringChanged   = 54,
    TransportPrioChanged    = 53,
    UnitProduction          = 68,
    UrgentProduction        = 69,
    WeaponPercent           = 70,
    WeaponAutoproduction    = 71,
    StorageGoodSwitch       = 72,
    VehicleProduction       = 73,
    DestroyBuildupVehicle   = 82,
    SpecialistProduction    = 75,
    InitMagicSideBar        = 57,
    InitGroupSideBar        = 58,
    InitAddSoldierSideBar   = 59,
    InitToolSideBar         = 60,
    InitWeaponSideBar       = 61,
    InitGoodsOutSideBar     = 62,
    InitTradeSideBar        = 63,
    InitStorageSideBar      = 64,
    InitEyeCatcherSideBar   = 65,
    InitAddVehicleSideBar   = 66,
    CloseSideBar            = 67,
    Morph2FoundationCart    = 76,
    CreateSettlement        = 77,
    Morph2Cart              = 78,
    VehicleUnload           = 79,
    CatapultLoad            = 80,
    DestroyWarMachine       = 81,
    ClearDialog             = 2,
    ZoomAreaState           = 83,
    CamSelection            = 84,
};

enum T_HOST_HANDLERS {
    StartState                   = 34,
    InitHostNetwork              = 1,
    InitClientNetwork            = 2,
    OnHostWait                   = 3,
    SearchHost                   = 4,
    WaitingForGameConnect        = 16,
    HostInitGame                 = 18,
    HostStartTick                = 19,
    RegClientConnect             = 23,
    WereConnectedForGame         = 24,
    ClientStartingGame           = 26,
    ClientGameInited             = 28,
    ClientStartTick              = 29,
    HostGameInited               = 31,
    GameSyncMsgGot               = 32,
    GameInGameMsgGot             = 33,
    ErrorState                   = 0,
    DoNothing                    = 36,
    ClientSearchesGameHost       = 35,
    ClientReceivesGameInfo       = 38,
    ClientLoginHost              = 40,
    ClientJoins                  = 39,
    ClientReceivePlayerData      = 42,
    ClientReceivePlayerPing      = 43,
    ClientLobbyPrepare           = 41,
    ResendPlayerData             = 6,
    ResendPlayerPing             = 44,
    InitGameStruct               = 7,
    HostPressedStart             = 8,
    ResendFinalPData             = 9,
    ChatLine                     = 45,
    GameAlreadyFull              = 46,
    GameAsyncMsgGot              = 47,
    AmIStillAlive                = 48,
    HeIsStillAlive               = 49,
    InitHostAfterLobby           = 50,
    InitClientAfterLobby         = 51,
    SendMapToClient              = 52,
    ClientReceiveMap             = 53,
    ClientLeavesMyGame           = 56,
    ClientWrongVersion           = 57,
    ClientWrongVersionAfterLobby = 58,
    PerformLeaveGame             = 59,
    SendChatLine                 = 61,
    HostChoseMap                 = 60,
    QuickMatchChoseMap           = 68,
    InviteAccepted               = 71,
    UserDataChange               = 62,
    KickClient                   = 63,
    WereKicked                   = 64,
    GameInGamePackedGot          = 65,
    GameSync0MsgGot              = 66,
    UserChangeSlots              = 67,
};

#endif //LOGIC_H
