#ifndef S4_MAIN_SETTLERS_H
#define S4_MAIN_SETTLERS_H

#include "DefineTransformers.h"

#define SETTLERS                          \
    X(0, SETTLER_NO_SETTLER)              \
    X(1, SETTLER_CARRIER)                 \
    X(2, SETTLER_DIGGER)                  \
    X(3, SETTLER_BUILDER)                 \
    X(4, SETTLER_WOODCUTTER)              \
    X(5, SETTLER_STONECUTTER)             \
    X(6, SETTLER_FORESTER)                \
    X(7, SETTLER_FARMERGRAIN)             \
    X(8, SETTLER_FARMERANIMALS)           \
    X(9, SETTLER_FISHER)                  \
    X(10, SETTLER_WATERWORKER)            \
    X(11, SETTLER_HUNTER)                 \
    X(12, SETTLER_SAWMILLWORKER)          \
    X(13, SETTLER_SMELTER)                \
    X(14, SETTLER_MINEWORKER)             \
    X(15, SETTLER_SMITH)                  \
    X(16, SETTLER_MILLER)                 \
    X(17, SETTLER_BAKER)                  \
    X(18, SETTLER_BUTCHER)                \
    X(19, SETTLER_SHIPYARDWORKER)         \
    X(20, SETTLER_HEALER)                 \
    X(21, SETTLER_CHARCOALMAKER)          \
    X(22, SETTLER_AMMOMAKER)              \
    X(23, SETTLER_VEHICLEMAKER)           \
    X(24, SETTLER_VINTNER)                \
    X(25, SETTLER_BEEKEEPER)              \
    X(26, SETTLER_MEADMAKER)              \
    X(27, SETTLER_AGAVEFARMER)            \
    X(28, SETTLER_TEQUILAMAKER)           \
    X(29, SETTLER_SWORDSMAN_01)           \
    X(30, SETTLER_SWORDSMAN_02)           \
    X(31, SETTLER_SWORDSMAN_03)           \
    X(32, SETTLER_BOWMAN_01)              \
    X(33, SETTLER_BOWMAN_02)              \
    X(34, SETTLER_BOWMAN_03)              \
    X(35, SETTLER_MEDIC_01)               \
    X(36, SETTLER_MEDIC_02)               \
    X(37, SETTLER_MEDIC_03)               \
    X(38, SETTLER_AXEWARRIOR_01)          \
    X(39, SETTLER_AXEWARRIOR_02)          \
    X(40, SETTLER_AXEWARRIOR_03)          \
    X(41, SETTLER_BLOWGUNWARRIOR_01)      \
    X(42, SETTLER_BLOWGUNWARRIOR_02)      \
    X(43, SETTLER_BLOWGUNWARRIOR_03)      \
    X(44, SETTLER_SQUADLEADER)            \
    X(45, SETTLER_PRIEST)                 \
    X(46, SETTLER_SABOTEUR)               \
    X(47, SETTLER_PIONEER)                \
    X(48, SETTLER_THIEF)                  \
    X(49, SETTLER_GEOLOGIST)              \
    X(50, SETTLER_GARDENER)               \
    X(51, SETTLER_LANDSCAPER)             \
    X(52, SETTLER_DARKGARDENER)           \
    X(53, SETTLER_MUSHROOMFARMER)         \
    X(54, SETTLER_SHAMAN)                 \
    X(55, SETTLER_SLAVED_SETTLER)         \
    X(56, SETTLER_TEMPLE_SERVANT)         \
    X(57, SETTLER_ANGEL_01)               \
    X(58, SETTLER_ANGEL_02)               \
    X(59, SETTLER_ANGEL_03)               \
    X(60, SETTLER_DONKEY)                 \
    X(61, SETTLER_BACKPACKCATAPULTIST_01) \
    X(62, SETTLER_BACKPACKCATAPULTIST_02) \
    X(63, SETTLER_BACKPACKCATAPULTIST_03) \
    X(64, SETTLER_SUNFLOWERFARMER)        \
    X(65, SETTLER_SUNFLOWEROILMAKER)      \
    X(66, SETTLER_MANACOPTERMASTER)

#define SETTLER_JOBS                \
    X(0, DUMMY_NONE)                \
    X(1, C_WALK)                    \
    X(2, C_WALK_AGAVE)              \
    X(3, C_WALK_AMMO)               \
    X(4, C_WALK_ARMOR)              \
    X(5, C_WALK_AXE)                \
    X(6, C_WALK_BATTLEAXE)          \
    X(7, C_WALK_BLOWGUN)            \
    X(8, C_WALK_BOARD)              \
    X(9, C_WALK_BOW)                \
    X(10, C_WALK_BREAD)             \
    X(11, C_WALK_COAL)              \
    X(12, C_WALK_FISH)              \
    X(13, C_WALK_FLOUR)             \
    X(14, C_WALK_GOAT)              \
    X(15, C_WALK_GOLDBAR)           \
    X(16, C_WALK_GOLDORE)           \
    X(17, C_WALK_GRAIN)             \
    X(18, C_WALK_GUNPOWDER)         \
    X(19, C_WALK_HAMMER)            \
    X(20, C_WALK_HONEY)             \
    X(21, C_WALK_IRONBAR)           \
    X(22, C_WALK_IRONORE)           \
    X(23, C_WALK_LOG)               \
    X(24, C_WALK_MEAD)              \
    X(25, C_WALK_MEAT)              \
    X(26, C_WALK_PICKAXE)           \
    X(27, C_WALK_PIG)               \
    X(28, C_WALK_ROD)               \
    X(29, C_WALK_SAW)               \
    X(30, C_WALK_SCYTHE)            \
    X(31, C_WALK_SHEEP)             \
    X(32, C_WALK_SHOVEL)            \
    X(33, C_WALK_STONE)             \
    X(34, C_WALK_SULFUR)            \
    X(35, C_WALK_SWORD)             \
    X(36, C_WALK_TEQUILA)           \
    X(37, C_WALK_WATER)             \
    X(38, C_WALK_WINE)              \
    X(39, C_WALK_BACKPACKCATAPULT)  \
    X(40, C_WALK_GOOSE)             \
    X(41, C_WALK_EXPLOSIVEARROW)    \
    X(42, C_WALK_SUNFLOWEROIL)      \
    X(43, C_WALK_SUNFLOWER)         \
    X(44, C_DOWN_NONE)              \
    X(45, C_IDLE1)                  \
    X(46, C_IDLE2)                  \
    X(47, C_IDLE3)                  \
    X(48, C_STRIKE1)                \
    X(49, C_STRIKE2)                \
    X(50, D_WALK)                   \
    X(51, D_WORK)                   \
    X(52, B_WALK)                   \
    X(53, B_WORK)                   \
    X(54, WC_WALK)                  \
    X(55, WC_WALK_LOG)              \
    X(56, WC_CUT_TREE)              \
    X(57, WC_PICKUP_LOG)            \
    X(58, ST_WALK)                  \
    X(59, ST_HACK)                  \
    X(60, ST_PICKUP)                \
    X(61, ST_WALK_STONE)            \
    X(62, F_WALK)                   \
    X(63, F_WALK_TREE)              \
    X(64, F_PLANT_SMALLTREE)        \
    X(65, FG_WALK)                  \
    X(66, FG_WALK_GRAIN)            \
    X(67, FG_WALK_SEED)             \
    X(68, FG_SEED_PLANTS)           \
    X(69, FG_CUT_GRAIN)             \
    X(70, FG_PICKUP_GRAIN)          \
    X(71, FG_WALK_SCYTHE)           \
    X(72, FA_WALK)                  \
    X(73, FA_WALK_WATER)            \
    X(74, FA_WALK_GRAIN)            \
    X(75, FA_PICKUP_WATER)          \
    X(76, FA_PICKUP_GRAIN)          \
    X(77, FA_WALK_EMPTY_FOOD)       \
    X(78, FA_WALK_FULL_FOOD)        \
    X(79, FA_FEED)                  \
    X(80, FI_WALK)                  \
    X(81, FI_WALK_FISH)             \
    X(82, FI_THROW_ROD)             \
    X(83, FI_PICKUP_FISH)           \
    X(84, FI_CATCH_FISH)            \
    X(85, FI_WORK)                  \
    X(86, W_WALK)                   \
    X(87, W_WALK_EMPTY_WATER)       \
    X(88, W_WALK_FULL_WATER)        \
    X(89, W_PICKUP_WATER)           \
    X(90, W_GET_WATER)              \
    X(91, H_WALK)                   \
    X(92, H_WALK_MEAT)              \
    X(93, H_PICKUP_MEAT)            \
    X(94, H_PICKUP_ANIMAL)          \
    X(95, H_SHOOT)                  \
    X(96, SW_WALK)                  \
    X(97, SW_WALK_LOG)              \
    X(98, SW_WALK_BOARD)            \
    X(99, SW_WORK)                  \
    X(100, SW_PICKUP_LOG)           \
    X(101, SW_PICKUP_BOARD)         \
    X(102, SME_WALK)                \
    X(103, SME_WALK_COAL)           \
    X(104, SME_WALK_GOLDBAR)        \
    X(105, SME_WALK_GOLDORE)        \
    X(106, SME_WALK_IRONBAR)        \
    X(107, SME_WALK_IRONORE)        \
    X(108, SME_PICKUP_COAL)         \
    X(109, SME_PICKUP_GOLDBAR)      \
    X(110, SME_PICKUP_GOLDORE)      \
    X(111, SME_PICKUP_IRONBAR)      \
    X(112, SME_WORK)                \
    X(113, SME_PICKUP_IRONORE)      \
    X(114, M_WALK)                  \
    X(115, M_PUSHIN_COAL)           \
    X(116, M_PUSHIN_IRONORE)        \
    X(117, M_PUSHIN_GOLDORE)        \
    X(118, M_PUSHIN_STONE)          \
    X(119, M_PUSHIN_SULFUR)         \
    X(120, M_PUSHOUT_COAL)          \
    X(121, M_PUSHOUT_IRONORE)       \
    X(122, M_PUSHOUT_GOLDORE)       \
    X(123, M_PUSHOUT_STONE)         \
    X(124, M_PUSHOUT_SULFUR)        \
    X(125, M_TIP_COAL)              \
    X(126, M_TIP_IRONORE)           \
    X(127, M_TIP_GOLDORE)           \
    X(128, M_TIP_STONE)             \
    X(129, M_TIP_SULFUR)            \
    X(130, S_WALK)                  \
    X(131, S_WALK_COAL)             \
    X(132, S_COOL_STEEL)            \
    X(133, S_WALK_GLOWSTEEL)        \
    X(134, S_WORK)                  \
    X(135, S_WALK_IRONBAR)          \
    X(136, S_WALK_STEEL)            \
    X(137, S_PICKUP_COAL)           \
    X(138, S_PICKUP_IRONBAR)        \
    X(139, S_PICKUP_STEEL)          \
    X(140, MI_WALK)                 \
    X(141, MI_WALK_GRAIN)           \
    X(142, MI_WALK_FLOUR)           \
    X(143, MI_PICKUP_GRAIN)         \
    X(144, MI_PICKUP_FLOUR)         \
    X(145, BA_WALK)                 \
    X(146, BA_WALK_FLOUR)           \
    X(147, BA_WALK_BREAD)           \
    X(148, BA_WALK_SHOVEL)          \
    X(149, BA_WALK_DOUGH)           \
    X(150, BA_WALK_WATER)           \
    X(151, BA_WORK_BREAD)           \
    X(152, BA_WORK_DOUGH)           \
    X(153, BA_SHOVEL_UP)            \
    X(154, BA_PICKUP_WATER)         \
    X(155, BA_PICKUP_FLOUR)         \
    X(156, BU_WALK)                 \
    X(157, BU_WALK_MEAT)            \
    X(158, BU_WALK_ANIMAL)          \
    X(159, BU_PICKUP_MEAT)          \
    X(160, BU_PICKUP_ANIMAL)        \
    X(161, SYW_WALK)                \
    X(162, SYW_WALK_BOARD)          \
    X(163, SYW_WALK_IRONBAR)        \
    X(164, SYW_PICKUP_BOARD)        \
    X(165, SYW_PICKUP_IRONBAR)      \
    X(166, SYW_WORK)                \
    X(167, HE_WALK)                 \
    X(168, HE_CONJURE)              \
    X(169, CO_WALK)                 \
    X(170, CO_WALK_LOG)             \
    X(171, CO_WALK_COAL)            \
    X(172, CO_PICKUP_COAL)          \
    X(173, CO_PICKUP_LOG)           \
    X(174, AM_WALK)                 \
    X(175, AM_WALK_FIRSTGOOD)       \
    X(176, AM_WALK_SECONDGOOD)      \
    X(177, AM_WALK_THIRDGOOD)       \
    X(178, AM_WALK_AMMO)            \
    X(179, AM_PICKUP_FIRSTGOOD)     \
    X(180, AM_PICKUP_SECONDGOOD)    \
    X(181, AM_PICKUP_THIRDGOOD)     \
    X(182, AM_PICKUP_AMMO)          \
    X(183, VM_WALK)                 \
    X(184, VM_WALK_STONE)           \
    X(185, VM_WALK_IRONBAR)         \
    X(186, VM_WALK_BOARD)           \
    X(187, VM_WORK)                 \
    X(188, VM_PICKUP_IRONBAR)       \
    X(189, VM_PICKUP_BOARD)         \
    X(190, VM_PICKUP_STONE)         \
    X(191, V_WALK)                  \
    X(192, V_WALK_PLANT)            \
    X(193, V_WALK_WINE)             \
    X(194, V_WALK_GRAPE)            \
    X(195, V_WALK_EMPTYGRAPE)       \
    X(196, V_WORK_PLANT)            \
    X(197, V_FILL_GRAPE)            \
    X(198, V_PICKUP_WINE)           \
    X(199, BK_WALK)                 \
    X(200, BK_WALK_BEEHIVE)         \
    X(201, BK_WALK_HONEY)           \
    X(202, BK_PICKUP_BEEHIVE)       \
    X(203, BK_PICKUP_HONEY)         \
    X(204, BK_WALK_EMPTYHONEY)      \
    X(205, BK_WORK)                 \
    X(206, MM_WALK)                 \
    X(207, MM_WALK_HONEY)           \
    X(208, MM_WALK_MEAD)            \
    X(209, MM_WALK_WATER)           \
    X(210, MM_PICKUP_HONEY)         \
    X(211, MM_PICKUP_MEAD)          \
    X(212, MM_PICKUP_WATER)         \
    X(213, AF_WALK)                 \
    X(214, AF_WALK_SMALLAGAVE)      \
    X(215, AF_WALK_AGAVE)           \
    X(216, AF_WALK_MACHETE)         \
    X(217, AF_PLANT_SMALLAGAVE)     \
    X(218, AF_PICKUP_AGAVE)         \
    X(219, AF_WORK_MACHETE)         \
    X(220, TM_WALK)                 \
    X(221, TM_WALK_AGAVE)           \
    X(222, TM_WALK_TEQUILA)         \
    X(223, TM_WALK_WATER)           \
    X(224, TM_PICKUP_AGAVE)         \
    X(225, TM_PICKUP_TEQUILA)       \
    X(226, TM_PICKUP_WATER)         \
    X(227, SML01_WALK)              \
    X(228, SML01_FIGHT)             \
    X(229, SML01_INVISIBLEWALK)     \
    X(230, SML02_WALK)              \
    X(231, SML02_FIGHT)             \
    X(232, SML02_INVISIBLEWALK)     \
    X(233, SML03_WALK)              \
    X(234, SML03_FIGHT)             \
    X(235, SML03_INVISIBLEWALK)     \
    X(236, BML01_WALK)              \
    X(237, BML01_SHOOT)             \
    X(238, BML01_PUTAWAY_BOW)       \
    X(239, BML01_THROW_STONE)       \
    X(240, BML01_FIGHT)             \
    X(241, BML01_INVISIBLEWALK)     \
    X(242, BML02_WALK)              \
    X(243, BML02_SHOOT)             \
    X(244, BML02_PUTAWAY_BOW)       \
    X(245, BML02_THROW_STONE)       \
    X(246, BML02_FIGHT)             \
    X(247, BML02_INVISIBLEWALK)     \
    X(248, BML03_WALK)              \
    X(249, BML03_SHOOT)             \
    X(250, BML03_PUTAWAY_BOW)       \
    X(251, BML03_THROW_STONE)       \
    X(252, BML03_FIGHT)             \
    X(253, BML03_INVISIBLEWALK)     \
    X(254, MEL01_WALK)              \
    X(255, MEL01_HEAL)              \
    X(256, MEL01_FIGHT)             \
    X(257, MEL01_INVISIBLEWALK)     \
    X(258, MEL02_WALK)              \
    X(259, MEL02_HEAL)              \
    X(260, MEL02_FIGHT)             \
    X(261, MEL02_INVISIBLEWALK)     \
    X(262, MEL03_WALK)              \
    X(263, MEL03_HEAL)              \
    X(264, MEL03_FIGHT)             \
    X(265, MEL03_INVISIBLEWALK)     \
    X(266, AWL01_WALK)              \
    X(267, AWL01_FIGHT)             \
    X(268, AWL01_INVISIBLEWALK)     \
    X(269, AWL02_WALK)              \
    X(270, AWL02_FIGHT)             \
    X(271, AWL02_INVISIBLEWALK)     \
    X(272, AWL03_WALK)              \
    X(273, AWL03_FIGHT)             \
    X(274, AWL03_INVISIBLEWALK)     \
    X(275, BGWL01_WALK)             \
    X(276, BGWL01_FIGHT)            \
    X(277, BGWL01_INVISIBLEWALK)    \
    X(278, BGWL02_WALK)             \
    X(279, BGWL02_FIGHT)            \
    X(280, BGWL02_INVISIBLEWALK)    \
    X(281, BGWL03_WALK)             \
    X(282, BGWL03_FIGHT)            \
    X(283, BGWL03_INVISIBLEWALK)    \
    X(284, SQL_WALK)                \
    X(285, SQL_FIGHT)               \
    X(286, SQL_INVISIBLEWALK)       \
    X(287, PR_WALK)                 \
    X(288, PR_CASTSPELL)            \
    X(289, PR_DUEL)                 \
    X(290, SA_WALK)                 \
    X(291, SA_GET_AXE)              \
    X(292, SA_GET_PICKAXE)          \
    X(293, SA_GET_SHOVEL)           \
    X(294, SA_WORK)                 \
    X(295, SA_WORK_AXE)             \
    X(296, SA_WORK_PICKAXE)         \
    X(297, SA_WORK_SHOVEL)          \
    X(298, P_WALK)                  \
    X(299, P_SHOVEL)                \
    X(300, P_WORK)                  \
    X(301, TH_WALK)                 \
    X(302, TH_WALK_GOOD)            \
    X(303, TH_STEAL)                \
    X(304, TH_DROP_GOOD)            \
    X(305, G_WALK)                  \
    X(306, G_WORK)                  \
    X(307, G_SEARCH)                \
    X(308, GA_WALK)                 \
    X(309, GA_WORK)                 \
    X(310, GA_BEAT_MUSHROOM)        \
    X(311, LS_WALK)                 \
    X(312, LS_WORK)                 \
    X(313, DG_WALK)                 \
    X(314, DG_SEED)                 \
    X(315, MF_WALK)                 \
    X(316, MF_WALK_SMALLMUSHROOM)   \
    X(317, MF_PLANT)                \
    X(318, MF_IMPATIENT_STAND)      \
    X(319, MF_POLISH)               \
    X(320, MF_PICKUP_MANA)          \
    X(321, MF_WALK_MANA)            \
    X(322, MF_CREATE_FARM)          \
    X(323, SHM_WALK)                \
    X(324, SHM_ENSLAVE)             \
    X(325, SS_WALK)                 \
    X(326, SS_POLISH)               \
    X(327, SS_FUDDEL)               \
    X(328, TS_WALK)                 \
    X(329, TS_WALK_WINE)            \
    X(330, TS_PICKUP_WINE)          \
    X(331, TS_WORK)                 \
    X(332, TS_ANIM)                 \
    X(333, A01_FLY)                 \
    X(334, A02_FLY)                 \
    X(335, A03_FLY)                 \
    X(336, DONKEY_WALK)             \
    X(337, DONKEY_STAND)            \
    X(338, DONKEY_WALK_EMPTYBASKET) \
    X(339, DONKEY_WALK_FULLBASKET)  \
    X(340, DONKEY_DROP_GOODS)       \
    X(341, BCL01_WALK)              \
    X(342, BCL01_FIGHT)             \
    X(343, BCL01_INVISIBLEWALK)     \
    X(344, BCL02_WALK)              \
    X(345, BCL02_FIGHT)             \
    X(346, BCL02_INVISIBLEWALK)     \
    X(347, BCL03_WALK)              \
    X(348, BCL03_FIGHT)             \
    X(349, BCL03_INVISIBLEWALK)     \
    X(350, SFF_WALK)                \
    X(351, SFF_WALK_PLANT)          \
    X(352, SFF_WALK_SMALL_PLANT)    \
    X(353, SFF_WALK_WATER)          \
    X(354, SFF_WORK)                \
    X(355, SFF_WORK_PLANT)          \
    X(356, SFF_WORK_WATER)          \
    X(357, SFF_PICKUP_PLANT)        \
    X(358, SOM_WALK)                \
    X(359, SOM_WALK_OIL)            \
    X(360, SOM_WALK_PLANT)          \
    X(361, SOM_PICKUP_PLANT)        \
    X(362, SOM_PICKUP_OIL)          \
    X(363, MCM_WALK)                \
    X(364, MCM_WORK)                \
    X(365, MCM_FUDDEL)              \
    X(366, MCM_FUDDEL2)

#define X(id, name) TO_ENUM(id, name)

enum S4_SETTLER_ENUM {
    SETTLERS SETTLER_MAX
};

enum S4_SETTLER_JOBS {
    SETTLER_JOBS SETTLER_JOB_MAX
};
#undef X

#define X TO_PAIR
inline SConfigTypeString s_sSettlerDefines[] = {
    SETTLERS
};
inline SConfigTypeString s_sSettlerJobDefines[] = {
    SETTLER_JOBS
};
#undef X

#endif // S4_MAIN_SETTLERS_H
