#ifndef S4_MAIN_SETTLERS_H
#define S4_MAIN_SETTLERS_H

#include "DefineTransformers.h"

#define SETTLERS \
    X(0, SETTLER_NO_SETTLER) \
    X(1, SETTLER_CARRIER) \
    X(2, SETTLER_DIGGER) \
    X(3, SETTLER_BUILDER) \
    X(4, SETTLER_WOODCUTTER) \
    X(5, SETTLER_STONECUTTER) \
    X(6, SETTLER_FORESTER) \
    X(7, SETTLER_FARMERGRAIN) \
    X(8, SETTLER_FARMERANIMALS) \
    X(9, SETTLER_FISHER) \
    X(10, SETTLER_WATERWORKER) \
    X(11, SETTLER_HUNTER) \
    X(12, SETTLER_SAWMILLWORKER) \
    X(13, SETTLER_SMELTER) \
    X(14, SETTLER_MINEWORKER) \
    X(15, SETTLER_SMITH) \
    X(16, SETTLER_MILLER) \
    X(17, SETTLER_BAKER) \
    X(18, SETTLER_BUTCHER) \
    X(19, SETTLER_SHIPYARDWORKER) \
    X(20, SETTLER_HEALER) \
    X(21, SETTLER_CHARCOALMAKER) \
    X(22, SETTLER_AMMOMAKER) \
    X(23, SETTLER_VEHICLEMAKER) \
    X(24, SETTLER_VINTNER) \
    X(25, SETTLER_BEEKEEPER) \
    X(26, SETTLER_MEADMAKER) \
    X(27, SETTLER_AGAVEFARMER) \
    X(28, SETTLER_TEQUILAMAKER) \
    X(29, SETTLER_SWORDSMAN_01) \
    X(30, SETTLER_SWORDSMAN_02) \
    X(31, SETTLER_SWORDSMAN_03) \
    X(32, SETTLER_BOWMAN_01) \
    X(33, SETTLER_BOWMAN_02) \
    X(34, SETTLER_BOWMAN_03) \
    X(35, SETTLER_MEDIC_01) \
    X(36, SETTLER_MEDIC_02) \
    X(37, SETTLER_MEDIC_03) \
    X(38, SETTLER_AXEWARRIOR_01) \
    X(39, SETTLER_AXEWARRIOR_02) \
    X(40, SETTLER_AXEWARRIOR_03) \
    X(41, SETTLER_BLOWGUNWARRIOR_01) \
    X(42, SETTLER_BLOWGUNWARRIOR_02) \
    X(43, SETTLER_BLOWGUNWARRIOR_03) \
    X(44, SETTLER_SQUADLEADER) \
    X(45, SETTLER_PRIEST) \
    X(46, SETTLER_SABOTEUR) \
    X(47, SETTLER_PIONEER) \
    X(48, SETTLER_THIEF) \
    X(49, SETTLER_GEOLOGIST) \
    X(50, SETTLER_GARDENER) \
    X(51, SETTLER_LANDSCAPER) \
    X(52, SETTLER_DARKGARDENER) \
    X(53, SETTLER_MUSHROOMFARMER) \
    X(54, SETTLER_SHAMAN) \
    X(55, SETTLER_SLAVED_SETTLER) \
    X(56, SETTLER_TEMPLE_SERVANT) \
    X(57, SETTLER_ANGEL_01) \
    X(58, SETTLER_ANGEL_02) \
    X(59, SETTLER_ANGEL_03) \
    X(60, SETTLER_DONKEY) \
    X(61, SETTLER_BACKPACKCATAPULTIST_01) \
    X(62, SETTLER_BACKPACKCATAPULTIST_02) \
    X(63, SETTLER_BACKPACKCATAPULTIST_03) \
    X(64, SETTLER_SUNFLOWERFARMER) \
    X(65, SETTLER_SUNFLOWEROILMAKER) \
    X(66, SETTLER_MANACOPTERMASTER)

#define X(id, name) TO_ENUM(id,name)

enum S4_SETTLER_ENUM {
    SETTLERS
    SETTLER_MAX
};
#undef X

#endif //S4_MAIN_SETTLERS_H
