#ifndef SOUND_H
#define SOUND_H

#include "DefineTransformers.h"

#define SOUNDS \
    X(0, SOUND_NO_SOUND) \
    X(1, SOUND_AMB_BIRD) \
    X(2, SOUND_AMB_CRUSHBIGHOUSE) \
    X(3, SOUND_AMB_CRUSHSMALLHOUSE) \
    X(4, SOUND_BUILD_DIG) \
    X(5, SOUND_BUILD_HAMMER) \
    X(6, SOUND_GUI_BUILDBUTTONDOWN) \
    X(7, SOUND_GUI_BUILDBUTTONUP) \
    X(8, SOUND_GUI_MAINBUTTONDOWN) \
    X(9, SOUND_GUI_MAINBUTTONUP) \
    X(10, SOUND_GUI_SUBBUTTONDOWN) \
    X(11, SOUND_GUI_SUBBUTTONUP) \
    X(12, SOUND_WORK_AXE) \
    X(13, SOUND_WORK_PICKAXE) \
    X(14, SOUND_WORK_PLANT) \
    X(15, SOUND_WORK_FARMERSEED) \
    X(16, SOUND_WORK_FARMERHARVEST) \
    X(17, SOUND_WORK_GETWATER) \
    X(18, SOUND_FIGHT_SWORD) \
    X(19, SOUND_FIGHT_BOW) \
    X(20, SOUND_WORK_MILLDRIVE) \
    X(21, SOUND_WORK_MELT_DOOR) \
    X(22, SOUND_WORK_MELT) \
    X(23, SOUND_WORK_SAWMILL) \
    X(24, SOUND_WORK_HEAL) \
    X(25, SOUND_ANIMAL_SEAGUL) \
    X(26, SOUND_ANIMAL_BEAR) \
    X(27, SOUND_ANIMAL_BUG) \
    X(28, SOUND_ANIMAL_FISH) \
    X(29, SOUND_ANIMAL_DOLPHIN) \
    X(30, SOUND_ANIMAL_DUG) \
    X(31, SOUND_ANIMAL_DONKEY) \
    X(32, SOUND_ANIMAL_JAGUAR) \
    X(33, SOUND_ANIMAL_SHEEP) \
    X(34, SOUND_ANIMAL_PIG) \
    X(35, SOUND_AMB_OCEAN) \
    X(36, SOUND_AMB_RIVER) \
    X(37, SOUND_WORK_GEOLOGIST) \
    X(38, SOUND_WORK_GEOLOGIST_FOUND) \
    X(39, SOUND_WORK_SMITH_HAMMER) \
    X(40, SOUND_WORK_SMITH_COOL) \
    X(41, SOUND_FIGHT_DIE) \
    X(42, SOUND_WORK_LOOKOUTTOWER) \
    X(43, SOUND_WORK_FISHER_RODOUT) \
    X(44, SOUND_WORK_FISHER_RODIN) \
    X(45, SOUND_WORK_FISHER_CATCH) \
    X(46, SOUND_IDLE_SNIFF) \
    X(47, SOUND_AMB_RAIN) \
    X(48, SOUND_AMB_FIRE) \
    X(49, SOUND_FIGHT_FIREBALL) \
    X(50, SOUND_WORK_MINER) \
    X(51, SOUND_AMB_THUNDER) \
    X(52, SOUND_MISC_BELL) \
    X(53, SOUND_AMB_BEES) \
    X(54, SOUND_MISC_HEAL) \
    X(55, SOUND_MAGIC_MAGIC01) \
    X(56, SOUND_MAGIC_MAGIC02) \
    X(57, SOUND_MAGIC_MAGIC03) \
    X(58, SOUND_MAGIC_MAGIC04) \
    X(59, SOUND_MAGIC_MAGIC05) \
    X(60, SOUND_MAGIC_FRIGHTENSOLDIERS) \
    X(61, SOUND_AMB_WIND) \
    X(62, SOUND_MAGIC_THORSHAMMER) \
    X(63, SOUND_MAGIC_TELEPORT) \
    X(64, SOUND_MAGIC_SMELTSNOW) \
    X(65, SOUND_MAGIC_GIFTOFGOD) \
    X(66, SOUND_MAGIC_FERTILITY) \
    X(67, SOUND_MAGIC_CHANGEGOOD) \
    X(68, SOUND_MAGIC_BARBARIAN) \
    X(69, SOUND_ANIMAL_BURN) \
    X(70, SOUND_MAGIC_BLOODRUSH) \
    X(71, SOUND_MAGIC_STONECURSE) \
    X(72, SOUND_MAGIC_DEFENSESHIELD) \
    X(73, SOUND_MAGIC_INCREASEANIMALS) \
    X(74, SOUND_MAGIC_FOODFISH) \
    X(75, SOUND_MAGIC_JUPITERS_LIGTHNING) \
    X(76, SOUND_GUI_BELL01) \
    X(77, SOUND_GUI_BELL02) \
    X(78, SOUND_GUI_HEAL01) \
    X(79, SOUND_GUI_HEAL02) \
    X(80, SOUND_AMB_DESERT) \
    X(81, SOUND_MAGIC_RAISERANK) \
    X(82, SOUND_MAGIC_FREEZESOLDIERS) \
    X(83, SOUND_MAGIC_REFRESHRESOURCES) \
    X(84, SOUND_MAGIC_PUNISHSOLDIERS) \
    X(85, SOUND_AMB_IMPACTTARGET) \
    X(86, SOUND_AMB_IMPACTWATER) \
    X(87, SOUND_IDLE_NEWSPAPER) \
    X(88, SOUND_CRUSH_SMALLBUILDING) \
    X(89, SOUND_CRUSH_BIGBUILDING) \
    X(90, SOUND_AMB_ATTACKBIGBUILDING) \
    X(91, SOUND_AMB_ATTACKSMALLBUILDING) \
    X(92, SOUND_AMB_WATERHITATARGET) \
    X(93, SOUND_MAGIC_SLAVE) \
    X(94, SOUND_GUI_CLICK01) \
    X(95, SOUND_GUI_CLICK02) \
    X(96, SOUND_WORK_TREEFALL) \
    X(97, SOUND_MAGIC_DARKDRY) \
    X(98, SOUND_MAGIC_MAGICDOOR) \
    X(99, SOUND_MAGIC_MANAKOPTERTURN) \
    X(100, SOUND_MAGIC_MANAKOPTERROTOR) \
    X(101, SOUND_EFFECTS_MANAKOPTEREXPLODE) \
    X(102, SOUND_FIGHT_BACKPACKCATAPULTIST) \
    X(103, SOUND_FIGHT_WARMACHINEBALLIST) \
    X(104, SOUND_EFFECTS_EXPLOSIONAMMOMAKER) \
    X(105, SOUND_AMB_HORN) \
    X(106, SOUND_AMB_SNORE) \
    X(107, SOUND_WORK_SUNFLOWER) \
    X(108, SOUND_AMB_MAGICSTONES)

#define X TO_ENUM

enum T_S4_SOUND {
    SOUNDS
};

#undef X

#define X TO_PAIR
SConfigTypeString s_sSoundDefines[] = {
    SOUNDS
};
#undef X

#endif //SOUND_H
