#ifndef TRIGGERS_H
#define TRIGGERS_H

#include "DefineTransformers.h"

#define TRIGGERS \
    X(0, PERMANENT) \
    X(1, TIMED) \
    X(2, EVENT) \
    X(3, TRIGGER_MILLER_WORK) \
    X(4, TRIGGER_BAKER_WORK) \
    X(5, TRIGGER_BAKER_SMALLSMOKE) \
    X(1, TRIGGER_COALMINE_PUSHOUT) \
    X(2, TRIGGER_COALMINE_PUSHIN) \
    X(6, TRIGGER_SMELTGOLD_MELTED) \
    X(7, TRIGGER_SMELTGOLD_SMOKE) \
    X(8, TRIGGER_SMELTIRON_MELTED) \
    X(9, TRIGGER_SMELTIRON_SMOKE) \
    X(10, TRIGGER_TOOLSMITH_SMOKE) \
    X(11, TRIGGER_TOOLSMITH_SMALLSMOKE) \
    X(12, TRIGGER_WEAPONSMITH_SMOKE) \
    X(13, TRIGGER_WEAPONSMITH_SMALLSMOKE) \
    X(14, TRIGGER_SMALLTOWER_DAMAGE_SMOKE) \
    X(15, TRIGGER_BIGTOWER_DAMAGE_SMOKE) \
    X(16, TRIGGER_LOOKOUT) \
    X(17, TRIGGER_START_SLOT0) \
    X(18, TRIGGER_START_SLOT1) \
    X(19, TRIGGER_START_SLOT2) \
    X(20, TRIGGER_START_SLOT3) \
    X(21, TRIGGER_START_SLOT4) \
    X(22, TRIGGER_START_SLOT5) \
    X(23, TRIGGER_START_SLOT6) \
    X(24, TRIGGER_START_SLOT7) \
    X(25, TRIGGER_START_SLOT8) \
    X(26, TRIGGER_START_SLOT9) \
    X(27, TRIGGER_STOP_SLOT0) \
    X(28, TRIGGER_STOP_SLOT1) \
    X(29, TRIGGER_STOP_SLOT2) \
    X(30, TRIGGER_STOP_SLOT3) \
    X(31, TRIGGER_STOP_SLOT4) \
    X(32, TRIGGER_STOP_SLOT5) \
    X(33, TRIGGER_STOP_SLOT6) \
    X(34, TRIGGER_STOP_SLOT7) \
    X(35, TRIGGER_STOP_SLOT8) \
    X(36, TRIGGER_STOP_SLOT9) \
    X(37, TRIGGER_CLEAR_SLOT0) \
    X(38, TRIGGER_CLEAR_SLOT1) \
    X(39, TRIGGER_CLEAR_SLOT2) \
    X(40, TRIGGER_CLEAR_SLOT3) \
    X(41, TRIGGER_CLEAR_SLOT4) \
    X(42, TRIGGER_CLEAR_SLOT5) \
    X(43, TRIGGER_CLEAR_SLOT6) \
    X(44, TRIGGER_CLEAR_SLOT7) \
    X(45, TRIGGER_CLEAR_SLOT8) \
    X(46, TRIGGER_CLEAR_SLOT9)

#define SEARCHES \
    X(0,SEARCH_NO_SEARCH) \
    X(1,SEARCH_FISH) \
    X(2,SEARCH_GRAIN_SEED_POS) \
    X(3,SEARCH_GRAIN) \
    X(4,SEARCH_AGAVE_SEED_POS) \
    X(5,SEARCH_AGAVE) \
    X(25,SEARCH_SUNFLOWER_SEED_POS) \
    X(26,SEARCH_SUNFLOWER) \
    X(6,SEARCH_TREE_SEED_POS) \
    X(7,SEARCH_TREE_SEED_POS_MAYA) \
    X(8,SEARCH_TREE) \
    X(9,SEARCH_VINE_SEED_POS) \
    X(10,SEARCH_VINE) \
    X(11,SEARCH_BEEHIVE_SEED_POS) \
    X(12,SEARCH_BEEHIVE) \
    X(13,SEARCH_MUSHROOM_SEED_POS) \
    X(14,SEARCH_MUSHROOM) \
    X(15,SEARCH_STONE) \
    X(16,SEARCH_VENISON) \
    X(17,SEARCH_WATER) \
    X(18,SEARCH_GOLD) \
    X(19,SEARCH_IRON) \
    X(20,SEARCH_COAL) \
    X(21,SEARCH_GRANITE) \
    X(22,SEARCH_SULFUR) \
    X(23,SEARCH_DARK_LAND) \
    X(24,SEARCH_GREEN_LAND)

#define X TO_ENUM

enum T_S4_TRIGGER {
    TRIGGERS
    MAX_TRIGGERS
};

enum T_S4_SEARCH {
    SEARCHES
};

#undef X

#endif //TRIGGERS_H
