# Generated FOLDER_MAP from BBSupportDbgReport analysis
# Copy this into your class_creator.py file

FOLDER_MAP = {
    "AI/": [
        "CAIAgent",
        "CAIAgentAttack",
        "CAIAgentDarkTribeAttack",
        "CAIAgentDarkTribeDarkGardeners",
        "CAIAgentDarkTribeManakopterHalls",
        "CAIAgentDarkTribeSquadManager",
        "CAIAgentEvaluation",
        "CAIAgentGeologists",
        "CAIAgentGlobalSuicideMission",
        "CAIAgentMovingHome",
        "CAIAgentPioneers",
        "CAIAgentPlayerBase",
        "CAIAgentSquads",
        "CAIAgentTaskScheduler",
        "CAIChambers",
        "CAIDarkTribePlayerAI",
        "CAIDarkTribeSectorAI",
        "CAIDarkTribeSectorAgent",
        "CAIEcoSectorAIEx",
        "CAIEnemySettlerInSectorIterator",
        "CAIEntityInfo",
        "CAIEntityInfoEx",
        "CAIEventQueue",
        "CAIGoalCache",
        "CAIMain",
        "CAINormalSectorAI",
        "CAINormalSectorAgent",
        "CAIPlayerAI",
        "CAIRegions",
        "CAIResourceMap",
        "CAIScheduler",
        "CAIScripting",
        "CAISectorAI",
        "CAITaskForce",
        "CAITaskForceEx",
        "CAITaskForceGroup",
        "CAITaskForcePriests",
        "CAITaskForcePriestsTrojan",
        "CAITaskForceShamans",
        "CAITaskForceSquad",
        "CAITaskForces",
        "CAIWatchTower",
        "CAIWatchTowerEx",
        "CAIWatchTowers",
        "CQuickScan",
        "CTaskForceWarMachines",
        "IAIDifficultyLevels",
        "IAIEnvironment",
    ],

    "AI/EcoManager/": [
        "CEcoManager",
        "CEcoManagerLeaf",
    ],

    "Ai/Dark Tribe/": [
        "CAIDarkTribe",
    ],

    "EventEngine/": [
        "IEventEngine",
    ],

    "LoadSave/": [
        "CGameChunkGeneral",
        "CMapFile",
        "CS4MemChunk",
        "CSavedPlayer",
    ],

    "Logic/": [
        "CBuildingSupplyPriority",
        "CDarkTribe",
        "CEcoSector",
        "CEcoSectorMgr",
        "CEffect",
        "CEffects",
        "CEndStatistic",
        "CFutureEvents",
        "CGoodTransportPriority",
        "CInfoExchange",
        "CInputProcessor",
        "CInternationalTrader",
        "CLogic",
        "CMagic",
        "CMagicSpell",
        "CNetInputProcessor",
        "CPlayerGameData",
        "CPlayerTradeInfo",
        "CStatistic",
        "CStatisticArchive",
        "CTransportMgr",
        "SPlayerStatistic",
    ],

    "Main/": [
        "CExtraCD",
        "CGameRun",
        "CGameSettings",
        "CGameStateHandler",
        "CGameType",
        "CMapGeneratorHost",
        "CPlayerManager",
        "CSoundManager",
        "CStringEngineEx",
        "CTextMsgHandler",
    ],

    "Main/States/": [
        "CGuiGameState",
        "CStateAOBriefing",
        "CStateAOCampaigns",
        "CStateAOSplash",
        "CStateBriefing",
        "CStateCampaign3X3",
        "CStateCampaignDark",
        "CStateCredits",
        "CStateEcoStatistic",
        "CStateEndStatistic",
        "CStateGame",
        "CStateLoadGame",
        "CStateLoadType",
        "CStateLobbyConnect",
        "CStateLobbyGameSettings",
        "CStateLobbyLoadMP",
        "CStateLobbyMapSettings",
        "CStateLobbyMultiplayerType",
        "CStateLocalType",
        "CStateMD2Briefing",
        "CStateMD2Campaigns",
        "CStateMDBriefing",
        "CStateMDCampaigns",
        "CStateMDRandomMapParameters",
        "CStateMainMenu",
        "CStateMessageBox",
        "CStateTutorial",
        "CStateVictoryScreen",
        "CStateVideo",
        "CStateXMD3Briefing",
        "CStateXMD3Campaigns",
    ],

    "MapObjects/": [
        "CCart",
        "CEntityToDoListMgr",
        "CGroupDestinations",
        "CGroupMgr",
        "CMapObjectMgr",
        "CObserverList",
        "CStdCargoCounter",
        "CStone",
        "CTree",
        "CVehicle",
        "CVehicleInfoMgr",
        "CVehicleIterator",
        "CVehicleMgr",
        "CWarriorBehavior",
        "CWheeler",
        "IEntity",
        "IMovingEntity",
    ],

    "MapObjects/Animal/": [
        "CAnimal",
        "CAnimalEffect",
        "CAnimalMgr",
        "CPossibleDirs",
    ],

    "MapObjects/Building/": [
        "CBarrackRole",
        "CBuilding",
        "CBuildingInfoMgr",
        "CBuildingMgr",
        "CBuildingSiteRole",
        "CDarkMushroomFarmRole",
        "CDarkTempleRole",
        "CFarmBuildingRole",
        "CGatherBuildingRole",
        "CLookoutTowerRole",
        "CMilitaryBuildingRole",
        "CMineRole",
        "CProductionBuildingRole",
        "CResidenceBuildingRole",
        "CSearchRoutines",
        "CSimpleBuildingRole",
        "CSmallTempleRole",
        "CStorageBuildingRole",
        "CTradingBuildingRole",
        "CWorkUpBuildingRole",
        "CWorkshopBuildingRole",
        "IBuildingRole",
    ],

    "MapObjects/Catapult/": [
        "CCatapult",
    ],

    "MapObjects/DecoObj/": [
        "CDecoObjMgr",
        "CDecoObject",
        "CMushroom",
        "CPlant",
        "CShadowHerb",
        "IDecoObject",
    ],

    "MapObjects/Pile/": [
        "CBuildingSitePileRole",
        "CDeliverPileRole",
        "CPile",
        "CPileMgr",
        "CPileObserverList",
        "CProductionPileRole",
        "CTradePileRole",
        "IPileRole",
    ],

    "MapObjects/Settler/": [
        "CBuilderRole",
        "CCarrierRole",
        "CDarkGardenerRole",
        "CDiggerRole",
        "CDonkeyRole",
        "CDoorRole",
        "CFleeRole",
        "CFreeWorkerRole",
        "CGardenerRole",
        "CGeologistRole",
        "CHouseWorkerRole",
        "CHunterRole",
        "CMushroomFarmerRole",
        "CPioneerRole",
        "CPriestRole",
        "CSettler",
        "CSettlerMgr",
        "CShamanRole",
        "CSlaveRole",
        "CSoldierRole",
        "CThiefRole",
        "CTowerSoldier",
        "ISettlerRole",
    ],

    "MapObjects/Ship/": [
        "CFerryShip",
        "CShip",
        "CTransportShip",
        "CWarShip",
    ],

    "Mapobjects/": [
        "CFlyingMgr",
        "CManakopter",
    ],

    "Mapobjects/Decoobj/": [
        "CHive",
    ],

    "Mapobjects/Settler/": [
        "CHJBMgr",
        "CHJBRole",
    ],

    "Net/": [
        "CClientList",
        "CGameHost",
        "CLanLobby",
        "CMsgStacks",
        "CSimpleNet",
        "INetworkEngine",
    ],

    "Pathing/": [
        "CAStar64",
        "CAStarTiling",
        "CAlliances",
        "CAreaList",
        "CDebugGridTest",
        "CFogging",
        "CInfluMap",
        "CLinks",
        "CScanner",
        "CSectors",
        "CShipMap",
        "CSquare",
        "CSquareVisited",
        "CTilesAndLinks",
        "CTilesEx",
        "CTiling",
        "CTilingWorld",
        "CVWList",
        "CWalking",
        "CWalkingBase",
        "CWalkingCatapult",
        "CWalkingShip",
        "CWarMap",
        "CWarMapNode",
        "CWater",
        "CWaterFlags",
    ],

    "Script/": [
        "CGameScriptManager",
        "CLua",
        "CScriptManager",
    ],

    "Source/": [
        "CDebitLevelManager",
        "CDynList",
        "CInvokeEvent",
        "CSchedule",
        "IAIEcoSectorAI",
    ],

    "Source/Compression/": [
        "LZBuffer",
        "LZHLCompressor",
        "LZHLDecompressor",
        "LZHLEncoder",
        "LZHLEncoderStat",
    ],

    "Source/ConfigManager/": [
        "CConfigManagerPtr",
        "CConfigVarIntArray",
    ],

    "Source/File/": [
        "CFileMgr",
    ],

    "Source/Xml/": [
        "Document",
        "Element",
        "GenerateContext",
        "NodeContainer",
        "Parser",
    ],

    "VideoEngine/": [
        "CBinkInterface",
        "IVideoEngine",
    ],

    "World/": [
        "CWorldManager",
    ],

}
